### ISSUE TITLE
Opening up for Hacktoberfest

### ISSUE THREAD

**Issue by daviscodesbugs** [daviscodesbugs/gamepiece-json#1]
Looking to get some PRs for Hacktoberfest?
This project is straightforward and easy for beginners and seasoned veterans alike.

I'm writing a collection of game piece lists for popular board games.
This is fairly straight forward, search for your favorite board game piece list and format it (generally following the other JSON files in this repo) to JSON.

**Comment by linuswillner** [comment]
Gonna get chess in the list 👍

**Comment by ghost** [comment]
Will do for carrom

**Comment by Lacaranian** [comment]
I might add one for Carcassonne (though I'm tempted to add some complex ones like Arkham Horror, I also want to retain my sanity).

**Comment by amritsinghcse** [comment]
Doing Monopoly.

**Comment by daviscodesbugs** [comment]
@SuperHaker You brave soul! 💪 Thanks!

**Comment by philtothetop** [comment]
Taking on BackGammon!

**Comment by matty22** [comment]
What about different versions of games? For example, there are a hundred different versions of Monopoly. Should those be submitted or not?

**Comment by daviscodesbugs** [comment]
@matty22 Right. For example, Harley Davidson monopoly will have different card names, so it should be a separate submission. If I was missing a token from my Harley Davidson monopoly, the piece list of Star Wars monopoly wouldn't help me figure out which one I'm missing.

**Comment by kartik95** [comment]
Added Cards Against Humanity. PR #26

**Comment by purnimamehta** [comment]
Working on Chinese Checkers 👍

**Comment by gendelbendel** [comment]
Gonna start working on Candy Land!

**Comment by daviscodesbugs** [comment]
If anybody wanted to convert [this card data](https://github.com/maltize/KingOfTokyo-CardList/blob/master/KingOfTokyo_CardList%20-%20EN.csv) to JSON and add it to the `king-of-tokyo.json` I'd greatly appreciate it!

**Comment by yarwest** [comment]
I'll take care of Chutes and Ladders :)

**Comment by okjulian** [comment]
Hope it's OK if I add [R](https://boardgamegeek.com/boardgame/112373/braverats) (also called BraveRats and made by Seiji Kanai, the creator of Love Letter)!

**Comment by daviscodesbugs** [comment]
Thanks to everyone who contributed. It's been a good hacktober. Feel free to keep adding!
