### ISSUE TITLE
Half done games and formatting/standardization

### ISSUE THREAD

**Issue by daviscodesbugs** [daviscodesbugs/gamepiece-json#35]
This project has had some awesome response for Hacktoberfest. If you're looking for a couple PRs for Hacktoberfest, this project is super easy and straightforward.

With so many contributions, each person does their game differently. I have some unit tests in place, but the games need some human review. In general games could use a standard formatting, and a specific structure. If you see something that can be standardized, feel free to make the change.

There are also a couple bigger games that are partially done, or games that are marked off that could still be improved on.

Take a look at the `Projects` tab for some quick and simple tasks that could be done

**Comment by Zenith-One** [comment]
I'm working on the deeds for Monopoly.

**Comment by Zenith-One** [comment]
Question: how much detail would you like on the deeds? I can do title only (which is the task) or I can also include the card 'data' (e.g. rent/mortage value/etc)

**Comment by daviscodesbugs** [comment]
@Zenith-One just titles fills the need, but if you're feeling ambitious, then the other data would be great (I'm going to add more detail to everything down the road). But for now the idea is that if I was missing a card, I could figure out which one it was.

**Comment by Zenith-One** [comment]
Doing chance next, followed by Comm. chest
