### ISSUE TITLE
Game Rule Books

### ISSUE THREAD

**Issue by daviscodesbugs** [daviscodesbugs/gamepiece-json#45]
If you're looking for some last minute contributions for Hacktoberfest, this is a quick easy contribution.

Find a game folder that doesn't yet have a PDF of the rules, google and find them, and include them in the folder. The PDF should have any full-page ads removed, named `rulebook-<game>` where `<game>` will be as it appears on the `.json` file. Also add the attribute `"file": "<filename>"` to the JSON file.

A list of tasks for rulebooks on the projects tab.

Thanks!

**Comment by juancuiule** [comment]
Hi, what about attributions in the pdf file?

**Comment by daviscodesbugs** [comment]
@juancuiule I don't understand what you mean.

**Comment by juancuiule** [comment]
What do I do if the pdf with the rules has attributions to a company or a person?

**Comment by daviscodesbugs** [comment]
Leave any attributions so that the work remains properly attributed to its creators.

**Comment by yarwest** [comment]
I am adding rules for Chutes and Ladders :)

**Comment by daviscodesbugs** [comment]
Thanks to everyone that contributed. We knocked it out in only a couple of days!
